#!/usr/bin/env bash
sudo dnf install -y \
    niri \
    xwayland-satellite \
    firefox \
    jetbrains-mono-fonts \
    alacritty \
    grim \
    fzf \
    slurp \
    swappy \
    wl-clipboard \
    thunar \
    xfce4-settings \
    udiskie \
    udisks2 \
    micro \
    fastfetch \
    brightnessctl \
    pulseaudio-utils \
    power-profiles-daemon \
    pavucontrol \
    pipewire \
    pipewire-pulseaudio \
    wireplumber \
    xdg-desktop-portal \
    xdg-desktop-portal-gnome \
    xdg-desktop-portal-gtk \
    wdisplays \
    kanshi \
    python3-pip \
    swaylock \
    swaybg \
    curl \
    xz \
    glib2 \
    okular \
    noctalia
