[bar.default]
background_opacity = 0.7
capsule_opacity = 0.5
center = [ "launcher", "clock", "wallpaper" ]
end = [ "clipboard", "volume", "battery", "notifications", "control-center" ]
margin_edge = 6
margin_ends = 6
position = "bottom"
start = [ "workspaces", "active_window" ]
widget_spacing = 12

[control_center]
hidden_tabs = [ "weather" ]
sidebar_section = "none"

[osd]
position = "top_right"

[shell]
font_family = "JetBrains Mono"
polkit_agent = true

    [shell.animation]
    speed = 1.3500000201165676

    [shell.launcher]
    app_grid = true
    categories = true
    compact = true
    fetch_exchange_rates = false
    sort_by_usage = false

    [shell.launcher.providers.calculator]
    global = false

    [shell.panel]
    clipboard_position = "bottom_right"
    control_center_position = "bottom_right"
    launcher_placement = "attached"
    open_near_click_control_center = true
    open_near_click_launcher = true
    session_placement = "floating"
    session_position = "bottom_right"
    wallpaper_placement = "floating"

[theme]
builtin = "Gruvbox"
community_palette = "Matecito"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "muted"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "qt", "starship" ]

[wallpaper]
directory = "~/Pictures/wallpapers"
transition_duration = 500
transition_on_startup = true

    [wallpaper.default]
    path = "~/Pictures/wallpapers/10.png"

    [wallpaper.last]
    path = "~/Pictures/wallpapers/10.png"

    [wallpaper.monitors.eDP-1]
    path = "~/Pictures/wallpapers/10.png"

[weather]
enabled = false

[widget.clock]
format = "{:%H:%M}"
anchor = true
tooltip_format = "{:%H:%M}"
vertical_format = "{:%H:%M}"


[widget.launcher]
glyph = "rocket"

[widget.notifications]
enabled = true

[widget.workspaces]
focused_output_only = true
hide_when_empty = true
labels_only_when_occupied = true
