[bar.default]
background_opacity = 0.6
capsule_opacity = 0.41
center = [ "launcher", "clock", "wallpaper" ]
end = [ "clipboard", "volume", "battery", "notifications", "control-center" ]
margin_edge = 4
margin_ends = 4
position = "bottom"
start = [ "workspaces" ]
widget_spacing = 16

[theme]
builtin = "Kanagawa"
community_palette = "Matecito"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "sway" ]
community_ids = [ "pywalfox" ]


[wallpaper.default]
path = "/usr/share/backgrounds/argentOs/wallhaven-138kjg.png"

[wallpaper.last]
path = "/usr/share/backgrounds/argentOs/wallhaven-138kjg.png"

[wallpaper.monitors.eDP-1]
path = "/usr/share/backgrounds/argentOs/wallhaven-138kjg.png"

[widget.clock]
format = "{:%H:%M, %a, %b %d}"

[widget.launcher]
glyph = "rocket"

[widget.notifications]
enabled = true

[widget.workspaces]
focused_output_only = true
hide_when_empty = true
labels_only_when_occupied = true
