# ~/.config/fuzzel/fuzzel.ini

[main]
font=Sans:size=11
icons-enabled=no
show-actions=no
terminal=alacritty

width=30
lines=10
horizontal-pad=15
vertical-pad=10
inner-pad=5

border-width=0
border-radius=0

[colors]
background=000000e6
text=ffffffff
match=00a8ffff
selection=333333e6
selection-text=ffffffff
border=444444ff

[border]
radius=0
width=0
